[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.24'
remappings = [
    '@delay-module=lib/delay-module/contracts/',
    '@roles-module=lib/roles-module/packages/evm/contracts/',
]

[rpc_endpoints]
gnosis = "${GNOSIS_RPC_URL}"
