[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.25'
remappings = [
    '@delay-module=lib/delay-module/contracts/',
    '@roles-module=lib/roles-module/packages/evm/contracts/',
    '@gnosispay-kit=lib/account-kit/contracts/',
    '@balancer-v2=lib/balancer-v2-monorepo/pkg/',
    '@chainlink=lib/chainlink/contracts/src/v0.8/',
]
cbor_metadata = true

[rpc_endpoints]
gnosis = "https://rpc.gnosis.gateway.fm"

[etherscan]
gnosis = { key = "${GNOSISSCAN_API_KEY}" }
