[package]
name = "app"
version = "0.1.0"
edition = "2021"


[dependencies]
alloy = { version = "0.11.1", features = ["eip712", "provider-anvil-api", "provider-anvil-node"] }
eyre = "0.6.12"
reqwest = "0.12.14"
serde_json = "1.0.139"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }
